### PR TITLE
Speed up TM simulation

### PR DESCRIPTION
**Pull request by cfbolz**
Hi Adam,

congrats on your work ;-). I guess that you ultimately don't care about the speed of Turing machine performance too much, since the point isn't to run them anyway. But I felt like it, so I optimized it somewhat. This is a bit at the expense of readability, so feel free to just reject the pull request.

As performance measurements I used 10**8 steps of `goldbach` and running `squaresaresmall` till it halts, with the 2 symbol version (the 4 symbol version has very similar results). I ran these on PyPy and Goldbach on CPython (not enough patience for `squaresaresmall`). The results improved as follows:

| VM | Benchmark | old (s) | new (s) | factor |
| --- | --- | --- | --- | --- |
| PyPy | Goldbach | 30.8 | 1.4 | 22x |
| CPython | Goldbach | 300.9 | 137.8 | 2.2x |
| PyPy | squaresaresmall | 363.0 | 31.9 | 11.4x |

This makes the code on PyPy a 70 MHz Turing machine emulator on my laptop ;-).

Cheers,

Carl Friedrich

### CODE REVIEW

**Comment by arigo** [comment]
Inspired me to try a simple .tm2-to-.c translator, using gcc to compile the final programs.  It runs squaresaresmall in 1.3 seconds.  Program attached to this issue (feel free to use or to ignore): run "python parse.py squaresaresmall.tm2 > tm.i && gcc -O2 tm.c".

[tm2-to-c.zip](https://github.com/adamyedidia/parsimony/files/263931/tm2-to-c.zip)

**Comment by adamyedidia** [comment]
Whoa, impressive! Thanks for doing this work. When you say that it's at the expense of readability, are you referring to the readability of the code, or did you change the output format at all?

**Comment by cfbolz** [comment]
no, I mean the readability of `tmsim.py`. Input output should be the same.

**Comment by adamyedidia** [comment]
Thanks very much to both of you! I have added both your contributions to the project. :)

**Pull request closed without merging**
